### PR TITLE
d-seams: Init at v1.0.1

### PR DESCRIPTION
**Pull request by HaoZeke**
This software: https:/dseams.info

### CODE REVIEW

**Comment by markuskowa** [comment]
Thank you for your contribution @HaoZeke! I am happy to take up your package in NixOS-QChem but may I ask why you have decided to integrate here and not directly in upstream nixpkgs?

**Comment by HaoZeke** [comment]
I @markuskowa, actually it has been waiting [for a review for over a month](https://github.com/NixOS/nixpkgs/pull/91611) now and I thought it'd be better suited to being here.

**Comment by markuskowa** [comment]
OK, I will review your PR in nixpkgs. The intent of this overlay is to have packages that are either not well enough tested yet or too hacky for nixpkgs. The long term goal is to move stable and clean derivations upstream. Since you are also the developer and have completely developed it on nix, I assume that your derivation is well working and suitable for upstream nixpkgs.

**Comment by HaoZeke** [comment]
@markuskowa thanks for the clarifications and being willing to review it! I maintain some packages upstream as well, and as you rightly noted this is developed from ground-up with nix, it'd be best suited for the upstream repo. Thanks also for putting this together!

**Pull request closed without merging**
